# Generated by Django 4.0.2 on 2022-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
