# Generated by Django 4.0.2 on 2022-02-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='message',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='messaging.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='messaging.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='messaging.user'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='message',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='messaging.user'),
        ),
    ]
